faq/urls.py
from django.conf.urls import url

from faq.views import faq

urlpatterns = [
	url(r'^faq/', faq, name="index"),
]

prof/urls.py
#-*-coding:utf-8 -*-
from django.conf.urls import url
from prof.views import profile, iplist, Good, Dead, backconnect_down, \
	backconnect_up, formsave, proxypay, monitoring, create_pay, email_jabber_wiews, qrcode_status

from prof.ajax import *

urlpatterns = [
    url(r'^profile/live/(?P<pk>\d+)/$', Good.as_view(), name='profile-good'),
    url(r'^profile/dead/(?P<pk>\d+)', Dead.as_view(), name='profile-dead'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^proxypay/$', proxypay, name='proxypay'),
    url(r'^monitoring/(?P<id>\d+)/$', monitoring, name='monitoring'),
    url(r'^formsave/$', formsave, name="formsave"),
    url(r'^profile/add/(?P<pk>\d+)/$', backconnect_up, name='backconnect_up'),
    url(r'^profile/del/(?P<pk>\d+)/$', backconnect_down, name='backconnect_down'),
    url(r'^iplist/(?P<pk>\d+)/$', iplist, name='iplist'),

    url(r'^oplata/$', create_pay, name='create_pay'),

    url(r'^pswc/$', password_change, name='pass_change'),
    url(r'^email_jabber_change/$', email_jabber_wiews, name='email_jabber_change'),
    url(r'^la/$', login_ajax, name='login_f'),
    url(r'^qrcode/$', qrcode_status, name='qrcode')
]

proxy/urls.py
#-*-coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from proxy.views import index, detail, ipdetail, change_view, req_form, \
    service, Ip, other, ajax_form, socks_online #City

from prof.views import profile



urlpatterns = [
    url(r"^search/(?P<count>[\w+|\w+\s+\w+|\W+\w+|\w+\S+\w+\S+\w+]+)$", detail, name='search'),
   # url(r"^city/(?P<city>[\w+|\w+\s+\w+|\W+\w+|\w+\S+\w+\S+\w+]+)$", City.as_view(), name='city'),
    url(r"^ip/(?P<id>[\w+]+)$", ipdetail, name='detail'),
    url(r'^service/', service, name='service'),
    url(r'^filter/', ajax_form, name='proxy-list'),
    url(r"^ip/(?P<host>[\w+])$", detail, name='search'),
    url(r'^$', index, name='index'),

    url(r'^change_view/$', change_view, name='change_view'),
    url(r'^socks_online/$', socks_online, name='socks_online'),
]


from . import ajax

urlajax = [
    url(r'ajax_all_country/', ajax.ajax_all_country, name='ajax_all_country'),
    url(r'ajax_dj_region/', ajax.ajax_dj_region, name='ajax_dj_region'),
    url(r'ajax_dj_city/', ajax.ajax_dj_city, name='ajax_dj_city'),
    url(r'ajax_post_region/', ajax.ajax_post_region, name='ajax_region_post'),
    url(r'ajax_search_form/', ajax.ajax_search_form, name='ajax_search'),
    url(r'ajax_all_vendors/', ajax.ajax_all_vendors, name='ajax_all_vendors'),
    url(r'ajax_search/', ajax.ajax_new_search, name='ajax_new_search'),
    url(r'ajax_ip_detail/', ajax.ajax_ip_detail, name='ajax_ip_detail'),

    url(r'ajax_continent/', ajax.ajax_continent, name='ajax-continent'),
    url(r'ajax_zone/', ajax.ajax_zone, name='ajax-zone'),
    url(r'ajax_code_country/', ajax.ajax_code_country, name='ajax-code-coutry'),
    url(r'ajax_code_region/', ajax.ajax_code_region, name='ajax-code-region'),
    url(r'ajax_code_postal/', ajax.ajax_code_postal, name='ajax-code-postal'),

]

urlpatterns += urlajax

proxyproject/urls.py
#-*-coding:utf-8 -*-
"""proxyproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('tick.urls', namespace='tickets')),
    url(r'', include('pay.urls',namespace='pay')),
    url(r'', include('proxy.urls',namespace='proxy')),
    #url(r'', include('vendor.urls',namespace='vendor')),
    url(r'', include('client.urls',namespace='client')),
    url(r'', include('prof.urls',namespace='prof')),
    url(r'', include('faq.urls', namespace='faq')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('referral.urls', namespace='referral')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


#urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from tickets.views import MyTicketListView, MyTicketDetailView, TicketCreateView


urlpatterns = patterns('',
    url(r'^my/$', login_required(MyTicketListView.as_view()), name='list'),
    url(r'^my/(?P<pk>\d+)/$', login_required(MyTicketDetailView.as_view()), name='detail'),
    url(r'^create/$', login_required(TicketCreateView.as_view()), name='create'),
)

templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta name="description" content="">
    <meta name="keywords" content="">
	<title>
		{% block title %}{% trans "" %}{% endblock title %}
	</title>
    <!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
    <!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
    <!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
    <!--[if (gte IE 9)|!(IE)]><!--> <!--<![endif]-->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "libs/bootstrap/css/bootstrap.min.css" %}">
    <!-- Header CSS (First Sections of Website: compress & paste after release from _header.css here) -->
    <link rel="stylesheet" type="text/css" href="{% static "css/styl.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/style-dj43.css" %}">
    <!-- Load CSS Compilled without JS -->
<link rel="stylesheet" href="{% static "compiled13.min.css" %}">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="shortcut icon" href="{% static "img/favicon/favicon.ico" %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static "img/favicon/apple-touch-icon.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "img/favicon/apple-touch-icon-72x72.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "img/favicon/apple-touch-icon-114x114.png" %}">

    <script src="{% static "libs/jquery/jquery-1.11.2.min.js" %}"></script>
    <script src="{% static "libs/bootstrap/js/bootstrap.js" %}"></script>

</head>

<body>
    {% block modal %}
    {% endblock modal %}
    <div  class="Page2Container container-fluid">
        <div class="P2CLine1 row-fluid">
            <div class="P2CL1Wrapp row-fluid">
                <h3 class="P2CL1WLogo col-lg-2 col-sm-4 col-xs-12">
                    proxybase.net
                </h3>

                <ul class="P2CL1WMenu col-lg-5 col-sm-12 col-xs-12">
                    <li>
                        <a href="{% url  'proxy:index' %}">
                        {% trans "Главная" %} </a>
                    </li>

                    <li>
                        <a href="{% url 'proxy:proxy-list' %}">
                            {% trans "Поиск" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'prof:proxypay' %}">
                            {% trans "Покупки" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'tickets:create' %}">
                            {% trans "Тикет" %}</a>
                            {% if user.is_authenticated %}
                                {% if count_tick != 0 %}
                                <span class="badge" style="margin: 0 0 0 5px;">{{count_tick}}</span>
                                {% endif %}
                            {% endif %}
                    </li>

        		   <li>
                        <a href="{% url 'faq:index' %}">{% trans "F.A.Q" %}</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'prof:profile'  %}">{% trans "Профиль" %}</a>
                        </li>
                      {% else %}
                        <li>
                            <a href="{% url 'modal_login' %}">{% trans "Вход" %}</a>
                        </li>
                    {% endif %}

                </ul>
                <div class="P2CL1WBalance col-lg-2 col-sm-4 col-xs-6" style="float: left !important;">
                    {% if request.user.is_authenticated %}
                    {% trans "Баланс:" %}{{ request.user.balance }}
                    {% endif %}
                </div>
                <div class="P2CL1WUser col-lg-2 col-sm-4 col-xs-6" style="margin-top: 20px;">

                    {# if request.user.is_authenticated #}
                    <div style="float: left; width: 110px;">
                        <span>Онлайн: {{ counts }}</span>
                    </div>
                    {# endif #}
                    {% if request.user.is_authenticated %}
                    <ul style="outline: 0px solid blue; list-style: none;">
                        <li>
                            <a href="{% url 'auth_logout' %}">{% trans "Выход" %}</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
                <div class="clearfix"></div>
            </div> <!-- P2CL1Wrapp -->

            <div class="clearfix"></div>
        </div> <!-- P2CLine1 -->

	           {% block content %}
                <div class="P2CLine2 row-fluid">

                    <div class="P2CL2Home col-lg-9 col-lg-offset-1 col-md-10">

                        <div class="P2CL2Block1 row-fluid">

                            <div class="P2CL2B1Left col-sm-6">

                                <div class="P2CL2B1LWrap">
                                    <h4>Top 5 Countries</h4>

                                    <div id="piechart" style="width: 100%;height:300px;"></div>
                                </div>
                            </div>

                            <div class="P2CL2B1Right col-sm-6">
                                <div class="P2CL2B1RWrap">
                                    <div id="regions_div" style="width: 100%; height: 350px;"></div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div> <!-- P2CL2Block1 -->
                            <div class="clearfix"></div>
                        </div> <!-- P2CL2Block2 -->
                    </div>
                    <div class="clearfix"></div>
                </div> <!-- P2CLine2 -->
                {% endblock content %}

                    <div class="clearfix"></div>
                </div> <!-- P2CLine3 -->
                <!-- FOOTER -->

                <!-- FOOTER -->
        	    <div class="clearfix"></div>
        	</div> <!-- Page2Container -->
            <div class="Footer">
                <div class="FWrap">
                    © 2017 proxybase.org
                </div>
            </div>
        	<!--[if lt IE 9]>
        	<script src="libs/html5shiv/es5-shim.min.js"></script>
        	<script src="libs/html5shiv/html5shiv.min.js"></script>
        	<script src="libs/html5shiv/html5shiv-printshiv.min.js"></script>
        	<script src="libs/respond/respond.min.js"></script>
        	<![endif]-->

            <!-- Load Scripts -->
        	<script>var scr = {"scripts":[
        		{"src" : "{% static "libs/modernizr/modernizr.js" %}", "async" : false},
        		{"src" : "{% static "libs/waypoints/waypoints.min.js" %}", "async" : false},
        		{"src" : "{% static "libs/animate/animate-css.js" %}", "async" : false},
        		{"src" : "{% static "libs/plugins-scroll/plugins-scroll.js" %}", "async" : false},
        		{"src" : "{% static "js/common.js" %}", "async" : false}
        		]};!function(t,n,r){"use strict";var c=function(t){if("[object Array]"!==Object.prototype.toString.call(t))return!1;for(var r=0;r<t.length;
                r++){var c=n.createElement("script"),e=t[r];c.src=e.src,c.async=e.async,n.body.appendChild(c)}return!0};
                t.addEventListener?t.addEventListener("load",function(){c(r.scripts);
                },!1):t.attachEvent?t.attachEvent("onload",function(){c(r.scripts)}):t.onload=function(){c(r.scripts)}}(window,document,scr);
        	</script>

<script>
	var supports3DTransforms =  document.body.style['webkitPerspective'] !== undefined ||
                            document.body.style['MozPerspective'] !== undefined;

    function linkfly( selector ) {
        if( supports3DTransforms ) {
            var nodes = document.querySelectorAll( selector );

            for( var i = 0, len = nodes.length; i < len; i++ ) {
                var node = nodes[i];

                if( !node.className || !node.className.match( /roll/g ) ) {
                    node.className += ' roll';
                    node.innerHTML = '<span data-title="'+ node.text +'">' + node.innerHTML + '</span>';
                    }
                };
            }
        }
    linkfly( 'a' );
</script>

<script>
$(document).ready(function(){
  var link = window.location.pathname;
  $('.P2CL1WMenu li a[href="'+link+'"]').closest('.P2CL1WMenu li ').addClass('active');

  if ( $(".P2CL1WMenu li").hasClass("active") ) {
  $('.P2CL1WMenu li a[href="'+link+'"]').closest('.P2CL1WMenu a ').addClass('a-active');
  }
  // if ($(document).height() <= $(window).height())
  //   $(".Footer").addClass("navbar-fixed-bottom");
});
</script>
</body>
</html>