faq/urls.py
from django.conf.urls import url

from faq.views import faq

urlpatterns = [
	url(r'^faq/', faq, name="index"),
]

prof/urls.py
#-*-coding:utf-8 -*-
from django.conf.urls import url
from prof.views import profile, iplist, Good, Dead, backconnect_down, \
	backconnect_up, formsave, proxypay, monitoring, create_pay, email_jabber_wiews, qrcode_status

from prof.ajax import *

urlpatterns = [
    url(r'^profile/live/(?P<pk>\d+)/$', Good.as_view(), name='profile-good'),
    url(r'^profile/dead/(?P<pk>\d+)', Dead.as_view(), name='profile-dead'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^proxypay/$', proxypay, name='proxypay'),
    url(r'^monitoring/(?P<id>\d+)/$', monitoring, name='monitoring'),
    url(r'^formsave/$', formsave, name="formsave"),
    url(r'^profile/add/(?P<pk>\d+)/$', backconnect_up, name='backconnect_up'),
    url(r'^profile/del/(?P<pk>\d+)/$', backconnect_down, name='backconnect_down'),
    url(r'^iplist/(?P<pk>\d+)/$', iplist, name='iplist'),

    url(r'^oplata/$', create_pay, name='create_pay'),

    url(r'^pswc/$', password_change, name='pass_change'),
    url(r'^email_jabber_change/$', email_jabber_wiews, name='email_jabber_change'),
    url(r'^la/$', login_ajax, name='login_f'),
    url(r'^qrcode/$', qrcode_status, name='qrcode')
]

proxy/urls.py
#-*-coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from proxy.views import index, detail, ipdetail, change_view, req_form, \
    service, Ip, other, ajax_form, socks_online #City

from prof.views import profile



urlpatterns = [
    url(r"^search/(?P<count>[\w+|\w+\s+\w+|\W+\w+|\w+\S+\w+\S+\w+]+)$", detail, name='search'),
   # url(r"^city/(?P<city>[\w+|\w+\s+\w+|\W+\w+|\w+\S+\w+\S+\w+]+)$", City.as_view(), name='city'),
    url(r"^ip/(?P<id>[\w+]+)$", ipdetail, name='detail'),
    url(r'^service/', service, name='service'),
    url(r'^filter/', ajax_form, name='proxy-list'),
    url(r"^ip/(?P<host>[\w+])$", detail, name='search'),
    url(r'^$', index, name='index'),

    url(r'^change_view/$', change_view, name='change_view'),
    url(r'^socks_online/$', socks_online, name='socks_online'),
]


from . import ajax

urlajax = [
    url(r'ajax_all_country/', ajax.ajax_all_country, name='ajax_all_country'),
    url(r'ajax_dj_region/', ajax.ajax_dj_region, name='ajax_dj_region'),
    url(r'ajax_dj_city/', ajax.ajax_dj_city, name='ajax_dj_city'),
    url(r'ajax_post_region/', ajax.ajax_post_region, name='ajax_region_post'),
    url(r'ajax_search_form/', ajax.ajax_search_form, name='ajax_search'),
    url(r'ajax_all_vendors/', ajax.ajax_all_vendors, name='ajax_all_vendors'),
    url(r'ajax_search/', ajax.ajax_new_search, name='ajax_new_search'),
    url(r'ajax_ip_detail/', ajax.ajax_ip_detail, name='ajax_ip_detail'),

    url(r'ajax_continent/', ajax.ajax_continent, name='ajax-continent'),
    url(r'ajax_zone/', ajax.ajax_zone, name='ajax-zone'),
    url(r'ajax_code_country/', ajax.ajax_code_country, name='ajax-code-coutry'),
    url(r'ajax_code_region/', ajax.ajax_code_region, name='ajax-code-region'),
    url(r'ajax_code_postal/', ajax.ajax_code_postal, name='ajax-code-postal'),

]

urlpatterns += urlajax

proxyproject/urls.py
#-*-coding:utf-8 -*-
"""proxyproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('tick.urls', namespace='tickets')),
    url(r'', include('pay.urls',namespace='pay')),
    url(r'', include('proxy.urls',namespace='proxy')),
    #url(r'', include('vendor.urls',namespace='vendor')),
    url(r'', include('client.urls',namespace='client')),
    url(r'', include('prof.urls',namespace='prof')),
    url(r'', include('faq.urls', namespace='faq')),
    url(r'', include('news.urls', namespace='news')),
    url(r'', include('referral.urls', namespace='referral')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


#urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tickets/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from tickets.views import MyTicketListView, MyTicketDetailView, TicketCreateView


urlpatterns = patterns('',
    url(r'^my/$', login_required(MyTicketListView.as_view()), name='list'),
    url(r'^my/(?P<pk>\d+)/$', login_required(MyTicketDetailView.as_view()), name='detail'),
    url(r'^create/$', login_required(TicketCreateView.as_view()), name='create'),
)

proxy/models.py
#-*-coding:utf-8 -*-
from django.db import models, connection
from django.utils.translation import ugettext_lazy as _

from django.contrib.postgres.fields import ArrayField
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings

from vendor.models import Vendors

User = settings.AUTH_USER_MODEL

TYPE_PROXY = (
    ('dp',_('Direct Proxy')),
    ('bp',_('Backconnect Proxy')),
)

ANONYM = (
    ('no',_(u'Нет Анонимности')),
    ('yes',_(u'Полная Анонимность')),
    ('medium',_(u'Средняя'))
)

TP = (
    ('http',_('HTTP')),
    ('https',_('HTTPS')),
    ('https_auth',_('HTTPS с авторизацией')),
    ('socks4',_('SOCKS4')),
    ('socks5',_('SOCKS5'))
)

class UpdateManager(models.Manager):
    def black(self, dic):
        cur = connection.cursor()
        val = [(v,k) for k,v in dic.items()]
        sql = "UPDATE proxy_proxy SET blacklist=%s WHERE ip = %s"
        cur.executemany(sql,val)


    def parser(self, dic):
        cur = connection.cursor()
        cur.execute("SELECT ip,port FROM proxy_proxy")
        fetch = cur.fetchall()
        host = ["{}".format(x[0]) for x in fetch]

        if host:
            s = {}
            for x in host:
                try:
                    s[x] = dic.pop(x)

                except Exception:
                    pass

        if s:
            sql = "UPDATE proxy_proxy SET port=%s WHERE ip = %s"
            d = [(v[2], k) for k,v in s.items()]

            cur.executemany(sql,d)

        dicts = [x for x in dic.values()]
        sql = """
            INSERT INTO proxy_proxy (
            vendor_id,ip,port,country,city,continent,
            country_code,lat,lon,postal_code,region_code,time_zone,tp, anonymity,checkers,timeout,gmt,time_region)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""

        cur.executemany(sql,dicts)


    def par(self, dic):
        cur = connection.cursor()
        up = timezone.now()

        val = [(v[0],up,k.split(':')[0],k.split(':')[1]) for k,v in dic.items() if v[0] == True]
        sql = "UPDATE proxy_proxy SET checkers=%s, update=%s WHERE ip = %s AND port = %s"

        cur.executemany(sql,val)

        val = [(v[0],k.split(':')[0],k.split(':')[1]) for k,v in dic.items() if v[0] == False]
        sql = "UPDATE proxy_proxy SET checkers=%s WHERE ip = %s AND port = %s"

        cur.executemany(sql,val)




@python_2_unicode_compatible
class CityProxy(models.Model):
    city = models.CharField(_(u'Город'), max_length=300, blank=True, null=True,unique=True)

    def __str__(self):
        return self.city

    class Meta:
        verbose_name = _(u'Город')
        verbose_name_plural = _(u'Города')


@python_2_unicode_compatible
class CountryProxy(models.Model):
    country = models.CharField(_(u'Страна'), max_length=300, blank=True, null=True, unique=True)

    def __str__(self):
        return self.country

    class Meta:
        verbose_name = _(u'Страна')
        verbose_name_plural = _(u'Страны')
        ordering = ('country',)


@python_2_unicode_compatible
class Worker(models.Model):
    ip = models.CharField(_(u"ip"),max_length=100, blank=True, null=True)
    jobs = models.IntegerField(_(u"колличество использования"),blank=True,default=0)
    flag = models.BooleanField(_(u"занят?"),default=False)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = _(u'Воркер')
        verbose_name_plural = _(u'Воркеры')


@python_2_unicode_compatible
class Proxy(models.Model):
    worker = models.ForeignKey(Worker,verbose_name=_(u"воркеры"))
    vendor = models.ForeignKey(User,verbose_name=_('Продавец'),blank=True, null=True)
    vendor_socks = models.ForeignKey(Vendors, verbose_name=_("Продавец сокса"), null=True, blank=True)

    ip = models.CharField(_(u'ip адрес'),max_length=1000,blank=True, null=True,db_index=True)
    port = models.CharField(_(u'порт'),max_length=1000,blank=True, null=True,db_index=True)

    ipreal = models.CharField(_(u'ip адрес (реальный ip)'),max_length=1000,blank=True,
        null=True,db_index=True)

    dns = models.CharField(_(u'dns'),max_length=1000,blank=True, null=True,db_index=True)
    usr = models.CharField(_(u'логин'),max_length=1000,blank=True, null=True, db_index=True)
    pswd = models.CharField(_(u'пароль'),max_length=1000,blank=True, null=True)

    country = models.CharField(_(u"Страна"),max_length=1000,blank=True,null=True)
    city = models.CharField(_(u"Город"),max_length=1000,blank=True,null=True)

    continent = models.CharField(_(u"Континент"),max_length=1000,blank=True,null=True)
    country_code = models.CharField(_(u"Код страны"),max_length=1000,blank=True,null=True)

    lat = models.CharField(_(u'Широта'), blank=True, null=True, max_length=1000)
    lon = models.CharField(_(u'Долгота'), blank=True, null=True, max_length=1000)

    postal_code = models.CharField(_("Почтовый код"),max_length=1000,blank=True,null=True)
    region_code = models.CharField(_("Код региона"),max_length=1000,blank=True,null=True)

    time_zone = models.CharField(_(u'Часовой пояс'), blank=True, null=True, max_length=1000)

    gmt = models.CharField(_(u'Gmt'),max_length=1000,blank=True, null=True)
    time_region = models.DateTimeField(_(u'Врями + зона'),blank=True, null=True)

    tp = models.CharField(_(u'Тип Прокси'),choices=TP,max_length=1000,blank=True,null=True)

    checkers = models.BooleanField(_(u'Проверен'),default=True)

    speed = models.CharField(_(u'скорость'),max_length=1000,blank=True,null=True)
    typeproxy = models.CharField(_(u'Тип Прокси'),max_length=1000,choices=TYPE_PROXY, default='dp', blank=True,null=True)

    anonymity = models.CharField(_(u'Анонимность'),choices=ANONYM, max_length=1000, blank=True, null=True)

    update = models.DateTimeField(_(u'Последние обновлеие'),blank=True,null=True)
    created = models.DateTimeField(_(u'создан'),blank=True,null=True)
    online = models.DateTimeField(_(u'онлайн'),blank=True,null=True)

    timeout = models.CharField(_(u'Отклик'),max_length=2000,blank=True,null=True)

    region = models.CharField(_("Область/Штат"),max_length=1000,blank=True,null=True)
    domain = models.CharField(_("Домен"),max_length=1000,blank=True,null=True)

    isp = models.CharField(_("isp провайдер"),max_length=1000,blank=True,null=True)


    blacklist = models.CharField(_(u"Блек-Лист"), max_length=5000, blank=True, null=True)
    auth = models.BooleanField(_(u"Auth?"), default=False)
    scan = models.BooleanField(_("не сканируеться"), default=False)

    #socks_list = models.BooleanField(_("Есть сокс в листе"), default=True)

    objects = models.Manager()
    geo = UpdateManager()


    def __str__(self):
        return "{0}:{1}".format(self.ip,self.port)

    def blacklist_names(self):
        bl = ', '.join([a.title for a in self.blacklist.all()])
        if bl:
            return bl
        else:
            return u"Нет в Блек-Лист'е"

    @property
    def hidden_ip(self):
        return ".".join(self.ip.split('.')[:2] + ['***','***'])

    @property
    def hidden_ipreal(self):
        return ".".join(self.ipreal.split('.')[:2] + ['***','***'])

    @property
    def black_split(self):
        return self.blacklist.split()

    @property
    def black_count(self):
        count = self.blacklist.split()
        return len(count)

    blacklist_names.short_description = "Black-List"

    @property
    def black_int(self):
        pass


    class Meta:
        verbose_name = _(u'Прокси')
        verbose_name_plural = _(u'Прокси')
        ordering = ('-update',)
        #unique_together = ("ip", "ipreal",  "vendor",)
        unique_together = ("ipreal",  "vendor",)


@python_2_unicode_compatible
class ProxyAuth(models.Model):
    worker = models.ManyToManyField(Worker,verbose_name=_(u"воркеры"))
    vendor = models.ForeignKey(User,verbose_name=_(u'Продавец'))
    iploc = models.CharField(_(u'локальный ip адрес'),max_length=255,blank=True, null=True)

    ip = models.CharField(_(u'ip адрес'),max_length=255,blank=True, null=True)
    ipreal = models.CharField(_(u'ip адрес (реальный ip)'),max_length=255,blank=True, null=True,db_index=True)
    port = models.CharField(_(u'порт'),max_length=255,blank=True, null=True)
    usr = models.CharField(_(u'логин'),max_length=255,blank=True, null=True, db_index=True)
    pswd = models.CharField(_(u'пароль'),max_length=255,blank=True, null=True)

    country = models.CharField(_(u"Страна"),max_length=255,blank=True,null=True)
    city = models.CharField(_(u"Город"),max_length=255,blank=True,null=True)

    continent = models.CharField(_(u"Континент"),max_length=100,blank=True,null=True)
    country_code = models.CharField(_(u"Код страны"),max_length=100,blank=True,null=True)

    lat = models.CharField(_(u'Широта'), blank=True, null=True, max_length=100)
    lon = models.CharField(_(u'Долгота'), blank=True, null=True, max_length=100)

    postal_code = models.CharField(_(u"Почтовый код"),max_length=100,blank=True,null=True)
    region_code = models.CharField(_(u"Код региона"),max_length=100,blank=True,null=True)

    time_zone = models.CharField(_(u'Часовой пояс'), blank=True, null=True, max_length=100)

    gmt = models.CharField(_(u'Gmt'),max_length=255,blank=True, null=True)
    time_region = models.DateTimeField(_(u'Врями + зона'),blank=True, null=True)

    tp = models.CharField(_(u'Тип Прокси'),choices=TP,max_length=20,blank=True,null=True)

    checkers = models.BooleanField(_(u'Проверен'),default=True)

    speed = models.CharField(_(u'скорость'),max_length=255,blank=True,null=True)
    typeproxy = models.CharField(_(u'Тип Прокси'),max_length=2,choices=TYPE_PROXY,blank=True,null=True)

    anonymity = models.CharField(_(u'Анонимность'),choices=ANONYM,max_length=10, blank=True, null=True)

    update = models.DateTimeField(_(u'Последние обновлеие'),blank=True,null=True)
    created = models.DateTimeField(_(u'создан'),blank=True,null=True)
    online = models.DateTimeField(_(u'онлайн'),blank=True,null=True)

templates/proxy/america1.html
{% for i in america %}
	socks5://{{ i }}<br>
{% endfor %}

templates/proxy/city.html
{% extends "base.html" %}

{% block content %}
	Записей {{ city|length }}<br>

	{% for c in city %}
		<a href="{% url 'proxy:detail' c.id %}" title="">{{ c.ipreal|truncatechars:8 }}:****</a><br>
	{% endfor %}

{% endblock content %}

templates/proxy/form.html
{% extends "base.html" %}

{% block content %}
	{% if form %}
		<div class="form-menu">
			<form action="" method="get">
    			{% csrf_token %}
    			{#{{ form.country.label_tag }}#}
    			{% for field in form %}
    				{{ field }}
    			{% endfor %}
    			<input type="submit" value="фильтровать"/>
    			
			</form>
		</div>
	{% endif %}
	{% if coun %}
		<p class="total-search">найдено {{ total }}</p>
		{% for proxy in coun %}
			<a class="proxy-search" href="{% url 'proxy:detail' proxy.id %}" 
			title="">{{ proxy.ipreal|truncatechars:9 }}***</a>
			<br>
		{% endfor %}
	{% endif %}
	<div class="pagination">
    	<span class="step-links">
        	{% if coun.has_previous %}
            	<a href="?page={{ coun.previous_page_number }}">назад</a>
        	{% endif %}

        {% if coun.number %}
        	<span class="current">
            	Страница {{ coun.number }} из {{ coun.paginator.num_pages }}.
        	</span>
        {% endif %}

        {% if coun.has_next %}
    		{% if GET_params %}
        		<a href="?{{GET_params.urlencode}}&amp;page={{ coun.next_page_number }}">вперед</a>
    		{% else %}
        		<a href="?page={{ coun.next_page_number }}">вперед</a>
    		{% endif %}
		{% endif %}
    	</span>
	</div>
	<script>
	$(document).ready(function() {
		$("#id_country").autocomplete({
			source: "{% url 'proxy:ajax-country' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	$(document).ready(function() {
		$("#id_city").autocomplete({
			source: "{% url 'proxy:ajax-city' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	$(document).ready(function() {
		$("#id_continent").autocomplete({
			source: "{% url 'proxy:ajax-continent' %}",
			selectFirst:true,
			minLength: 1,
		
			});
		});
	$(document).ready(function() {
		$("#id_time_zone").autocomplete({
			source: "{% url 'proxy:ajax-zone' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	$(document).ready(function() {
		$("#id_country_code").autocomplete({
			source: "{% url 'proxy:ajax-code-coutry' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	$(document).ready(function() {
		$("#id_postal_code").autocomplete({
			source: "{% url 'proxy:ajax-code-postal' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	$(document).ready(function() {
		$("#id_region_code").autocomplete({
			source: "{% url 'proxy:ajax-code-region' %}",
			selectFirst:true,
			minLength: 2,
		
			});
		});
	</script>
{% endblock %}

templates/proxy/iplist.html
{% extends "base.html" %}

{% block content %}
всего {{ proxy|length }}<br>
	{% for i in proxy %}
		{{ i.ipreal }}<br>
	{% endfor %}
{% endblock %}

templates/proxy/link.html
{% for link in links %}
    <a target="_blank" href="{{ link.url }}">{{ link.title }}</a>
{% endfor %}

templates/proxy/profile.html
{% extends "base.html" %}

{% block content %}

<p> купленные списки</p>
	
	{% for proxy in iplist %}
		<li><a href="{% url "proxy:iplist" proxy.id %}" title="купленные списки">{{ proxy.namelist }}</a>
		</li>
	{% endfor %}
	<br>

<p> купленные беки </p>
	<ul>
	{% for p in port %}
		<li>
			{{request.user.get_name_split}}:{{p.password}}@109.236.88.132:{{ p.port }} 
			реальный ip -> {{p.ipreal}}
		</li>
	{% endfor %}
	</ul>
<br>



в состоянии проверки: {{ proxys_all|length }}<br>
{% if good %}
	Рабочих {{ good|length }}<br>
	{% for p in good %}
		{{ p.ip }}:{{ p.port }}<br>
	{% endfor %}
{% endif %}

{% if dead %}
	Нерабочих {{ dead|length }}<br>
	{% for p in dead %}
		{{ p.ip }}:{{ p.port }}<br>
	{% endfor %}
{% endif %}

{% if proxys_off %}
	Нерабочих {{ proxys_off|length }}<br>
{% endif %}
{% if proxys_on %}
	Рабочих {{ proxys_on|length }}<br>
{% endif %}

{% if not dead and not good %}
	<a href="{% url 'proxy:profile-dead' profile.id %}" title="">Нерабочих</a>
	<a href="{% url 'proxy:profile-good' profile.id %}" title="">Рабочих</a>
{% endif %}
{% endblock %}

templates/proxy/result.html
{% extends "base.html" %}

{% block content %}
	{% if coun %}
		<p>найдено {{ total }}</p>
		{% for proxy in coun %}
			<a href="{% url 'proxy:detail' proxy.id %}" title="">{{ proxy.ip }}:{{ proxy.port }}</a><br>
		{% endfor %}
	{% endif %}
	<div class="pagination">
    	<span class="step-links">
        	{% if coun.has_previous %}
            	<a href="?page={{ coun.previous_page_number }}">назад</a>
        	{% endif %}

        {% if coun.number %}
        	<span class="current">
            	Страница {{ coun.number }} из {{ coun.paginator.num_pages }}.
        	</span>
        {% endif %}

        	{% if coun.has_next %}
            	<a href="?page={{ coun.next_page_number }}">вперед</a>
        	{% endif %}
    	</span>
	</div>
{% endblock %}

templates/proxy/result_list_auth.html
{% block content %}


coun_max {{ ip|length }}

всего {{ ip|length }}<br>
	{% if sniff %}
		{{ sniff }}<br>
	{% endif %}
	{% for i in ip %}
		{{ i }}<br>
	{% endfor %}
{% endblock %}

templates/proxy/result_list_auth_new.html
{% block content %}

	{% for k in val1 %}
		{{ ip1 }}:{{ k }}<br>
	{% endfor %}
	{% for k in val2 %}
		{{ ip2 }}:{{ k }}<br>
	{% endfor %}

{% endblock %}

templates/proxy/service.html
{% extends "base.html" %}

{% block content %}
Покупетели<br>
{% for user in users %}
	{% if user.clients_set.all %}
		{% for client in user.clients_set.all %}
			<a href="" title="">{{ client }}</a>

		{% endfor %}
	{% endif %}
{% endfor %}
<br>
Продавцы<br>
{% for user in users %}
		
			<a href="{% url 'prof:profile' user.id %}" title="">{{ user }}</a>
			<br>
			
		
	
{% endfor %}
{% endblock %}

templates/proxy/template.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" value="фильтровать"/>
    </form>
    {% for obj in filter %}
        {#{{ obj.country }} {{ obj.ip }}<br />#}
    {% endfor %}
{% endblock %}

templates/proxy/usa_list.html
{% for u in object_list %}
	{{ u.ip }}:{{ u.port }}
{% endfor %}